import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:objectbox/objectbox.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';

import '../../models/note.dart';
import '../../models/study_plan.dart';
import '../../models/sutta.dart';
import '../../objectbox.g.dart'; // generated by build_runner

/// Singleton wrapper around the ObjectBox [Store].
///
/// Provides typed [Box] accessors for every entity.
/// Opened once in [main] and injected via Riverpod providers.
class ObjectBoxStore {
  final Store _store;

  ObjectBoxStore._(this._store);

  static Future<ObjectBoxStore> open() async {
    final docsDir = await getApplicationDocumentsDirectory();
    final dbPath = p.join(docsDir.path, 'buddhist_study_db');
    final store = await openStore(directory: dbPath);
    return ObjectBoxStore._(store);
  }

  // ─── Typed box accessors ─────────────────────────────────────────────

  Box<Sutta> get suttas => _store.box<Sutta>();
  Box<StudyPlan> get studyPlans => _store.box<StudyPlan>();
  Box<StudyPlanProgress> get progress => _store.box<StudyPlanProgress>();
  Box<Note> get notes => _store.box<Note>();

  Store get raw => _store;

  void close() => _store.close();
}

// ─── Providers (overridden in main.dart with real values) ──────────────────

final objectBoxStoreProvider = Provider<ObjectBoxStore>(
  (ref) => throw UnimplementedError('override in main'),
);

final sharedPrefsProvider = Provider<dynamic>(
  (ref) => throw UnimplementedError('override in main'),
);

// ─── Box providers ─────────────────────────────────────────────────────────

final suttaBoxProvider = Provider<Box<Sutta>>(
  (ref) => ref.watch(objectBoxStoreProvider).suttas,
);

final studyPlanBoxProvider = Provider<Box<StudyPlan>>(
  (ref) => ref.watch(objectBoxStoreProvider).studyPlans,
);

final progressBoxProvider = Provider<Box<StudyPlanProgress>>(
  (ref) => ref.watch(objectBoxStoreProvider).progress,
);

final noteBoxProvider = Provider<Box<Note>>(
  (ref) => ref.watch(objectBoxStoreProvider).notes,
);
