import { BookOpen, Search, Compass, StickyNote, ExternalLink } from "lucide-react";

export default function AboutPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-8">
      <h1 className="mb-6 font-serif text-3xl font-bold text-fg">About</h1>

      <div className="prose-buddhist space-y-6 text-fg-muted">
        <p className="text-lg">
          A personal study interface for exploring the Pāli Canon and Buddhist teachings —
          semantic search, thematic study plans, offline sutta reading, and note-taking,
          all in one place.
        </p>

        <h2 className="font-serif text-xl font-bold text-fg">What's here</h2>

        <div className="grid gap-4 sm:grid-cols-2">
          <div className="rounded-xl border border-bg-border bg-bg-card p-5">
            <BookOpen size={24} className="mb-2 text-burgundy" />
            <h3 className="font-serif font-bold text-fg">4,200+ Suttas offline</h3>
            <p className="mt-1 text-sm">
              Bhikkhu Sujato's English translations of the Pāli Canon, fully available
              without internet.
            </p>
          </div>
          <div className="rounded-xl border border-bg-border bg-bg-card p-5">
            <Search size={24} className="mb-2 text-saffron-dark" />
            <h3 className="font-serif font-bold text-fg">Semantic search</h3>
            <p className="mt-1 text-sm">
              Vector search powered by Qdrant — finds suttas by meaning, not just keywords.
              Also covers 4,494+ curated resources (articles, books, talks).
            </p>
          </div>
          <div className="rounded-xl border border-bg-border bg-bg-card p-5">
            <Compass size={24} className="mb-2 text-sage" />
            <h3 className="font-serif font-bold text-fg">166 study plans</h3>
            <p className="mt-1 text-sm">
              Thematic clusters generated by HDBSCAN over sutta embeddings — follow a
              plan, track progress, navigate prev/next.
            </p>
          </div>
          <div className="rounded-xl border border-bg-border bg-bg-card p-5">
            <StickyNote size={24} className="mb-2 text-lotus" />
            <h3 className="font-serif font-bold text-fg">Note-taking</h3>
            <p className="mt-1 text-sm">
              Annotate passages while reading. Notes are stored locally in your browser,
              organised by nikāya, study plan, or sutta.
            </p>
          </div>
        </div>

        <h2 className="font-serif text-xl font-bold text-fg">Credits</h2>
        <p>
          The content library (4,494+ resources, courses, metadata) is sourced from{" "}
          <a
            href="https://www.buddhistuniversity.net"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-0.5 text-saffron-dark underline hover:text-saffron"
          >
            The Open Buddhist University
            <ExternalLink size={12} className="ml-0.5" />
          </a>
          , a remarkable free library maintained by its contributors. This project
          is an independent fork — it is not affiliated with or endorsed by OBU.
        </p>
        <p>
          Sutta translations are by{" "}
          <a
            href="https://suttacentral.net"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-0.5 text-saffron-dark underline hover:text-saffron"
          >
            Bhikkhu Sujato via SuttaCentral
            <ExternalLink size={12} className="ml-0.5" />
          </a>
          , licensed under CC BY 4.0.
        </p>

        <div className="rounded-xl border border-saffron/20 bg-saffron/5 p-6 text-center">
          <p className="font-serif text-lg italic text-fg">
            &ldquo;An insincere and evil friend is more to be feared than a wild beast; a wild
            beast may wound your body, but an evil friend will wound your mind.&rdquo;
          </p>
          <p className="mt-2 text-sm text-saffron-dark">&mdash; The Buddha</p>
        </div>
      </div>
    </div>
  );
}
