"""
Sutta-specific search and study plan tools.
Queries the 'buddhist_suttas' Qdrant collection.
Used by both the FastAPI routes and the MCP server.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

from qdrant_client import QdrantClient
from qdrant_client.models import Filter, FieldCondition, MatchValue, MatchAny, Range

from search.ingestion.qdrant_setup import QDRANT_URL
from search.ingestion.embedder import get_embedder

SUTTA_COLLECTION = "buddhist_suttas"
REPO_ROOT = Path(__file__).parent.parent.parent
STUDY_PLANS_FILE = REPO_ROOT / "search" / "data" / "study_plans.json"
TEXTS_DIR = REPO_ROOT / "frontend" / "public" / "content" / "texts"


def is_local(sutta_id: str) -> bool:
    """Return True if a local text file exists for this sutta."""
    return (TEXTS_DIR / f"{sutta_id}.json").exists()

_sutta_client: QdrantClient | None = None


def get_sutta_client() -> QdrantClient:
    global _sutta_client
    if _sutta_client is None:
        _sutta_client = QdrantClient(url=QDRANT_URL)
    return _sutta_client


# ---------------------------------------------------------------------------
# Study Plans (loaded from JSON file generated by generate_study_plans.py)
# ---------------------------------------------------------------------------

@lru_cache(maxsize=1)
def _load_study_plans() -> list[dict]:
    """Load and cache study plans from JSON. Call invalidate_plans_cache() to reload."""
    if not STUDY_PLANS_FILE.exists():
        return []
    return json.loads(STUDY_PLANS_FILE.read_text())


def invalidate_plans_cache() -> None:
    """Force reload of study plans (call after regeneration)."""
    _load_study_plans.cache_clear()


def list_study_plans(
    theme_category: str | None = None,
    nikaya: str | None = None,
    min_size: int = 5,
    limit: int = 50,
) -> list[dict]:
    """
    List all available study plans, optionally filtered.

    Args:
        theme_category: Filter by theme (practice, doctrine, ethics, cosmology,
                        community, psychology, narrative, poetry, mixed)
        nikaya: Filter plans containing this nikaya (an, sn, mn, dn, ...)
        min_size: Minimum number of suttas in a plan
        limit: Maximum number of plans to return

    Returns:
        List of plan summaries (without the full sutta list for brevity)
    """
    plans = _load_study_plans()
    results = []

    for plan in plans:
        if plan["size"] < min_size:
            continue
        if theme_category and plan.get("theme_category") != theme_category:
            continue
        if nikaya and nikaya not in plan.get("nikaya_breakdown", {}):
            continue

        # Return summary (without suttas list — use get_study_plan for details)
        results.append({
            "cluster_id": plan["cluster_id"],
            "name": plan["name"],
            "description": plan["description"],
            "keywords": plan["keywords"],
            "theme_category": plan["theme_category"],
            "nikaya_breakdown": plan["nikaya_breakdown"],
            "size": plan["size"],
            "reading_minutes": plan["reading_minutes"],
        })

        if len(results) >= limit:
            break

    return results


def get_study_plan(cluster_id: int) -> dict | None:
    """
    Get the full study plan for a cluster, including the ordered sutta sequence.

    Args:
        cluster_id: Integer cluster ID (from /study-plans list)

    Returns:
        Full plan with ordered suttas list (each sutta includes local:bool), or None if not found
    """
    plans = _load_study_plans()
    for plan in plans:
        if plan["cluster_id"] == cluster_id:
            # Enrich each sutta with local availability
            enriched = dict(plan)
            enriched["suttas"] = [
                {**s, "local": is_local(s.get("sutta_id", ""))}
                for s in plan.get("suttas", [])
            ]
            return enriched
    return None


def find_study_plan_by_topic(topic: str, limit: int = 5) -> list[dict]:
    """
    Find study plans semantically matching a topic using Qdrant vector search.

    Searches for suttas matching the topic, then returns the study plans
    of the clusters they belong to.

    Args:
        topic: Natural language topic (e.g. "mindfulness", "dependent origination")
        limit: Number of plans to return

    Returns:
        List of matching study plans (summaries), ranked by relevance
    """
    embedder = get_embedder()
    client = get_sutta_client()

    query_vector = embedder.encode_query(topic)

    # Search for matching suttas
    results = client.query_points(
        collection_name=SUTTA_COLLECTION,
        query=query_vector,
        limit=30,
        with_payload=True,
    ).points

    # Collect clusters represented in results, ranked by hit count + score
    from collections import defaultdict
    cluster_scores: dict[int, float] = defaultdict(float)
    for hit in results:
        cid = hit.payload.get("cluster_id")
        if cid is not None:
            cluster_scores[int(cid)] += hit.score

    top_clusters = sorted(cluster_scores.items(), key=lambda x: -x[1])[:limit]

    # Load matching plans
    plans = _load_study_plans()
    plan_by_id = {p["cluster_id"]: p for p in plans}

    matched = []
    for cluster_id, _score in top_clusters:
        if cluster_id in plan_by_id:
            plan = plan_by_id[cluster_id]
            matched.append({
                "cluster_id": plan["cluster_id"],
                "name": plan["name"],
                "description": plan["description"],
                "keywords": plan["keywords"],
                "theme_category": plan["theme_category"],
                "nikaya_breakdown": plan["nikaya_breakdown"],
                "size": plan["size"],
                "reading_minutes": plan["reading_minutes"],
                "relevance_score": round(_score, 3),
            })

    return matched


# ---------------------------------------------------------------------------
# Sutta Search
# ---------------------------------------------------------------------------

def search_suttas(
    query: str,
    nikaya: str | None = None,
    cluster_id: int | None = None,
    min_words: int | None = None,
    max_words: int | None = None,
    limit: int = 10,
) -> list[dict]:
    """
    Semantic search across 4167+ Sujato English sutta translations.

    Args:
        query: Natural language query (e.g. "breath meditation", "what is anattā?")
        nikaya: Filter by collection: an, sn, mn, dn, dhp, ud, iti, snp, thag, thig, ja
        cluster_id: Filter to a specific thematic cluster
        min_words / max_words: Filter by sutta length in words
        limit: Number of results (max 20)

    Returns:
        List of matching suttas with score, sutta_id, title, blurb, url, cluster
    """
    embedder = get_embedder()
    client = get_sutta_client()

    query_vector = embedder.encode_query(query)

    # Build filter
    conditions = []
    if nikaya:
        conditions.append(FieldCondition(key="nikaya", match=MatchValue(value=nikaya)))
    if cluster_id is not None:
        conditions.append(FieldCondition(key="cluster_id", match=MatchValue(value=cluster_id)))
    if min_words is not None or max_words is not None:
        conditions.append(FieldCondition(
            key="word_count",
            range=Range(gte=min_words, lte=max_words),
        ))

    qdrant_filter = Filter(must=conditions) if conditions else None

    results = client.query_points(
        collection_name=SUTTA_COLLECTION,
        query=query_vector,
        query_filter=qdrant_filter,
        limit=min(limit, 20),
        with_payload=True,
    ).points

    return [
        {
            "score": round(hit.score, 4),
            "sutta_id": hit.payload.get("sutta_id"),
            "nikaya": hit.payload.get("nikaya"),
            "nikaya_name": hit.payload.get("nikaya_name"),
            "title": hit.payload.get("title"),
            "blurb": hit.payload.get("blurb") or "",
            "word_count": hit.payload.get("word_count"),
            "difficulty": hit.payload.get("difficulty"),
            "cluster_id": hit.payload.get("cluster_id"),
            "cluster_name": hit.payload.get("cluster_name"),
            "url": hit.payload.get("url"),
            "local": is_local(hit.payload.get("sutta_id", "")),
        }
        for hit in results
    ]


def get_sutta(sutta_id: str) -> dict | None:
    """
    Get a specific sutta by its ID (e.g. 'dn2', 'mn36', 'sn12.15').

    Returns full payload including blurb, cluster info, and URL.
    """
    import hashlib
    point_id = int(hashlib.md5(sutta_id.encode()).hexdigest()[:16], 16) % (2**63)
    client = get_sutta_client()

    results = client.retrieve(
        collection_name=SUTTA_COLLECTION,
        ids=[point_id],
        with_payload=True,
    )
    if not results:
        return None

    p = results[0].payload
    sid = p.get("sutta_id", "")
    return {
        "sutta_id": sid,
        "nikaya": p.get("nikaya"),
        "nikaya_name": p.get("nikaya_name"),
        "title": p.get("title"),
        "blurb": p.get("blurb") or "",
        "word_count": p.get("word_count"),
        "segment_count": p.get("segment_count"),
        "difficulty": p.get("difficulty"),
        "translator": p.get("translator"),
        "cluster_id": p.get("cluster_id"),
        "cluster_name": p.get("cluster_name"),
        "url": p.get("url"),
        "local": is_local(sid),
    }


def get_similar_suttas(sutta_id: str, limit: int = 8) -> list[dict]:
    """
    Find suttas most similar to a given sutta (by vector proximity).

    Args:
        sutta_id: Reference sutta (e.g. 'mn10', 'sn47.1')
        limit: Number of similar suttas to return

    Returns:
        List of similar suttas ordered by similarity score
    """
    import hashlib
    point_id = int(hashlib.md5(sutta_id.encode()).hexdigest()[:16], 16) % (2**63)
    client = get_sutta_client()

    # Use Qdrant's recommend API (vector of the sutta itself as query)
    results = client.query_points(
        collection_name=SUTTA_COLLECTION,
        query=point_id,  # use existing vector by ID
        limit=limit + 1,  # +1 to exclude self
        with_payload=True,
    ).points

    return [
        {
            "score": round(hit.score, 4),
            "sutta_id": hit.payload.get("sutta_id"),
            "nikaya": hit.payload.get("nikaya"),
            "nikaya_name": hit.payload.get("nikaya_name", ""),
            "title": hit.payload.get("title"),
            "blurb": (hit.payload.get("blurb") or "")[:120],
            "word_count": hit.payload.get("word_count"),
            "difficulty": hit.payload.get("difficulty"),
            "cluster_id": hit.payload.get("cluster_id"),
            "cluster_name": hit.payload.get("cluster_name"),
            "url": hit.payload.get("url"),
            "local": is_local(hit.payload.get("sutta_id", "")),
        }
        for hit in results
        if hit.payload.get("sutta_id") != sutta_id  # exclude self
    ][:limit]
